routes/web.php
<?php

use App\Http\Controllers\admin\AdminController;
use App\Http\Controllers\admin\ChaletsController;
use App\Http\Controllers\admin\PropertyOwnerController;
use App\Http\Controllers\admin\TestimoniosController;
use App\Http\Controllers\auth\LoginController;
use App\Http\Controllers\auth\RegisterController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\admin\AboutController;

use App\Http\Controllers\admin\ContactController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\SliderController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/login_view', [LoginController::class, 'showAdminLoginForm'])->name('admin_login');


Route::post('/login', [LoginController::class, 'login']);

Route::group(['prefix' => 'admin_panel','as' => 'admin_panel.'], function () {

    Route::group(['middleware' => 'auth:admin'], function () {

        Route::resource('about', AboutController::class);

        Route::resource('testimonials', TestimoniosController::class);
        Route::get('/del_testimonials/{id}', [TestimoniosController::class, 'destroy']);


        Route::resource('admin', AdminController::class);
        Route::get('/del_admin/{id}', [AdminController::class, 'destroy']);
        Route::get('/changePass/{id}', [AdminController::class, 'changePass']);
        Route::post('changePass/updatepass/{id}', [AdminController::class, 'updatepass']);

        
        Route::resource('property_owner', PropertyOwnerController::class);
        Route::get('/del_owner/{id}', [PropertyOwnerController::class, 'destroy']);
        Route::get('/changePass/{id}', [PropertyOwnerController::class, 'changePass']);
        Route::post('changePass/updatepass/{id}', [PropertyOwnerController::class, 'updatepass']);

       
        
     


        Route::resource('Chalets', ChaletsController::class);
        Route::get('/del_Chalets/{id}', [ChaletsController::class, 'destroy']);

        Route::resource('contact', ContactController::class);
        Route::get('/delContact/{id}', [ContactController::class, 'destroy']);

        Route::get('/logout', [LoginController::class, 'logout']);

    });
});




Route::get('/', [HomeController::class, 'index']);
Route::get('/view_chalet/{id}', [HomeController::class, 'view_chalet'])->name('views');
Route::get('/view_about', [HomeController::class, 'view_about']);

Route::get('/view_contact', [HomeController::class, 'view_contact']);

Route::post('/contact', [ContactController::class, 'store']);

Route::get('/privacy', function () {
    return view('privacy');
});
 //Clear route cache
 Route::get('/route-cache', function() {
     \Artisan::call('route:cache');
     return 'Routes cache cleared';
 });

 //Clear config cache
 Route::get('/config-cache', function() {
     \Artisan::call('config:cache');
     return 'Config cache cleared';
 }); 

 // Clear application cache
 Route::get('/clear-cache', function() {
     \Artisan::call('cache:clear');
     return 'Application cache cleared';
 });

 // Clear view cache
 Route::get('/view-clear', function() {
     \Artisan::call('view:clear');
     return 'View cache cleared';
 });

 // Clear cache using reoptimized class
 Route::get('/optimize-clear', function() {
     \Artisan::call('optimize:clear');
     return 'View cache cleared';
 });




     

   

      

app/Http/Controllers/admin/PropertyOwnerController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class PropertyOwnerController extends Controller
{


    public function index()
    {
        $item = User::orderBy('created_at', 'desc')->get();
        return view('admin.property_owner.index', compact('item' ));
    }



    public function create()
    {
        return view('admin.property_owner.create');
    }



    public function store(Request $request)
    {
        $item = User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => Hash::make($request->password),
        
        ]);

        return redirect(route('admin_panel.property_owner.index'));
    }

    public function edit(Request $request, $id)
    {
        $item = User::find($id);
        return view('admin.property_owner.edit', compact('item'));
    }


    public function show($id)
    {
        $item = User::find($id);
        return view('admin.property_owner.show', compact('item'));
    }




    public function update(Request $request, $id)
    {
        $item = User::find($id);
        $item->update([
            'name' => $request->name,
            'email' => $request->email,
            'password' => $request->password,
        ]);
        return redirect(route('admin_panel.property_owner.index'));

    }

    public function destroy($id)
    {
        $item = User::find($id);
        $item->delete();
        return redirect(route('admin_panel.property_owner.index'));
    }


    public function changePass(Request $request, $id)
    {
        $item = User::find($id);
        return view('admin.property_owner.edit-pass', compact('item'));
    }

    public function updatepass(Request $request, $id)
    {
        $validateData = $request->validate([
            'password' => 'required',
            'confirm_password' => 'required|same:password',
        ]);

        $item = User::find($id);
        $item->update([
            'password'=> Hash::make($request->password),
        ]);
        return redirect(route('admin_panel.property_owner.index'));
    }


  


}

resources/views/admin/property_owner/create.blade.php
@extends('admin.dashboard')

@section('content')

    <div id="content" class="main-content">
        <!--  BEGIN BREADCRUMBS  -->
        <div class="secondary-nav">
            <div class="breadcrumbs-container" data-page-heading="Analytics">
                <header class="header navbar navbar-expand-sm">
                    <a href="javascript:void(0);" class="btn-toggle sidebarCollapse" data-placement="bottom">
                        <svg xmlns="http://www.w3.org/2000/.svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-menu"><line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="18" x2="21" y2="18"></line></svg>
                    </a>
                    <div class="d-flex breadcrumb-content">
                        <div class="page-header">

                            <div class="page-title">
                            </div>

                            <nav class="breadcrumb-style-one" aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item ">  Property Owner </li>
                                    <li class="breadcrumb-item active">   Property Owner  </li>
                                </ol>
                            </nav>

                        </div>
                    </div>
                </header>
            </div>
        </div>
        <br>
        <!--  END BREADCRUMBS  -->
        <div class="row layout-spacing " >

            <!-- Content -->
            <div class="col-12" style="margin:2% 2% auto;">
                <div class="user-profile ">
                    <div class="widget-content widget-content-area">
                        <div class=" " style="padding:2% 2% 0px; " >
                            <h3 class="">Add Admin</h3>
                        </div>

                        <div class="" style="padding: 2%;">
                            <div class="container">
                                <form class=" g-3" method="post" action="{{route('admin_panel.property_owner.store')}}" enctype="multipart/form-data" >
                                    @method('POST')
                                    @csrf
                                    @if ($errors->any())

                                        <div class="alert alert-danger">

                                            <ul style="list-style: none;margin:0">

                                                @foreach ($errors->all() as $error)

                                                    <li>{{ $error }}</li>

                                                @endforeach

                                            </ul>

                                        </div>

                                    @endif
                                    <div class="row">

                                    <div class="col-md-12">
                                            <h5>  name </h5>
                                            <input type="text" class="form-control"  name="name" required>
                                        </div>
                                        <div class="col-md-12">
                                            <h5>  Email </h5>
                                            <input type="email" class="form-control"  name="email" required>
                                        </div>
                                        <div class="col-md-12">
                                            <h5>  Password </h5>
                                            <input type="password" class="form-control"  name="password" required>
                                        </div>
                                        <div class="col-12">
                                        <div class="text-center">
                                        <button type="submit" class="btn btn-primary">Add
                                        </button>
                                        </div>
                                    </div>

                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>



        <!--  BEGIN FOOTER  -->
    @include('admin.layouts.footer')
    <!--  END FOOTER  -->

    </div>



@endsection

resources/views/admin/property_owner/edit-pass.blade.php
@extends('admin.dashboard')

@section('content')

    <div id="content" class="main-content">
        <!--  BEGIN BREADCRUMBS  -->
        <div class="secondary-nav">
            <div class="breadcrumbs-container" data-page-heading="Analytics">
                <header class="header navbar navbar-expand-sm">
                    <a href="javascript:void(0);" class="btn-toggle sidebarCollapse" data-placement="bottom">
                        <svg xmlns="http://www.w3.org/2000/.svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-menu"><line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="18" x2="21" y2="18"></line></svg>
                    </a>
                    <div class="d-flex breadcrumb-content">
                        <div class="page-header">

                            <div class="page-title">
                            </div>

                            <nav class="breadcrumb-style-one" aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                <li class="breadcrumb-item ">  Property Owner </li>
                                    <li class="breadcrumb-item active"> Add Property Owner </li>
                                </ol>
                            </nav>

                        </div>
                    </div>
                </header>
            </div>
        </div>
        <br>
        <!--  END BREADCRUMBS  -->
        <div class="row layout-spacing " >

            <!-- Content -->
            <div class="col-12" style="margin:2% 2% auto;">
                <div class="user-profile ">
                    <div class="widget-content widget-content-area">
                        <div class=" " style="padding:2% 2% 0px; " >
                            <h3 class="">Edit Property Owner Password </h3>
                        </div>

                        <div class="" style="padding: 2%;">
                            <div class="container">
                                <form class=" g-3" method="post" action="updatepass/{{$item->id}}" enctype="multipart/form-data" >
                                @method('post')
                                    @csrf
                                    @if ($errors->any())

                                        <div class="alert alert-danger">

                                            <ul style="list-style: none;margin:0">

                                                @foreach ($errors->all() as $error)

                                                    <li>{{ $error }}</li>

                                                @endforeach

                                            </ul>

                                        </div>

                                    @endif
                               

                                    <div class="col-md-12">
                                        <label for="inputEmail4" class="form-label">  Password </label>
                                        <input type="password" class="form-control"  name="password"  value="">
                                    </div>

                                    <div class="col-md-12">
                                        <label for="inputEmail4" class="form-label">  confirm password </label>
                                        <input type="password" class="form-control"  name="confirm_password"  value="">
                                    </div>

                
                                    <div class="col-12">
                                        <div class="text-center">
                                        <button type="submit" class="btn btn-primary">Update</button>
                                        </div>
                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <!--  BEGIN FOOTER  -->
    @include('admin.layouts.footer')
    <!--  END FOOTER  -->

    </div>



@endsection

resources/views/admin/property_owner/edit.blade.php
@extends('admin.dashboard')

@section('content')

    <div id="content" class="main-content">
        <!--  BEGIN BREADCRUMBS  -->
        <div class="secondary-nav">
            <div class="breadcrumbs-container" data-page-heading="Analytics">
                <header class="header navbar navbar-expand-sm">
                    <a href="javascript:void(0);" class="btn-toggle sidebarCollapse" data-placement="bottom">
                        <svg xmlns="http://www.w3.org/2000/.svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-menu"><line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="18" x2="21" y2="18"></line></svg>
                    </a>
                    <div class="d-flex breadcrumb-content">
                        <div class="page-header">

                            <div class="page-title">
                            </div>

                            <nav class="breadcrumb-style-one" aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                <li class="breadcrumb-item ">  Property Owner </li>
                                    <li class="breadcrumb-item active"> Add  Property Owner </li>
                                </ol>
                            </nav>

                        </div>
                    </div>
                </header>
            </div>
        </div>
        <br>
        <!--  END BREADCRUMBS  -->
        <div class="row layout-spacing " >

            <!-- Content -->
            <div class="col-12" style="margin:2% 2% auto;">
                <div class="user-profile ">
                    <div class="widget-content widget-content-area">
                        <div class=" " style="padding:2% 2% 0px; " >
                            <h3 class="">Edit  Property Owner  </h3>
                        </div>

                        <div class="" style="padding: 2%;">
                            <div class="container">
                                <form class=" g-3" method="post" action="{{route('admin_panel.property_owner.update',$item->id)}}" enctype="multipart/form-data" >
                                @method('PATCH')
                                    @csrf
                                    @if ($errors->any())

                                        <div class="alert alert-danger">

                                            <ul style="list-style: none;margin:0">

                                                @foreach ($errors->all() as $error)

                                                    <li>{{ $error }}</li>

                                                @endforeach

                                            </ul>

                                        </div>

                                    @endif
                               

                                    <div class="col-md-12">
                                        <label for="inputEmail4" class="form-label">  Name </label>
                                        <input type="text" class="form-control"  name="name"  value="{{$item->name}}">
                                    </div>

                                    <div class="col-md-12">
                                        <label for="inputEmail4" class="form-label">  Email </label>
                                        <input type="email" class="form-control"  name="email"  value="{{$item->email}}">
                                    </div>
                                        <input type="hidden" class="form-control"  name="password"  value="{{$item->password}}">

                    

                                    <div class="col-12">
                                        <div class="text-center">
                                        <button type="submit" class="btn btn-primary">Update</button>
                                        </div>
                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <!--  BEGIN FOOTER  -->
    @include('admin.layouts.footer')
    <!--  END FOOTER  -->

    </div>



@endsection

resources/views/admin/property_owner/index.blade.php
@extends('admin.dashboard')

@section('content')
<div id="content" class="main-content">
    <!--  BEGIN BREADCRUMBS  -->
    <div class="secondary-nav">
        <div class="breadcrumbs-container" data-page-heading="Analytics">
            <header class="header navbar navbar-expand-sm">
                <a href="javascript:void(0);" class="btn-toggle sidebarCollapse" data-placement="bottom">
                    <svg xmlns="http://www.w3.org/2000/.svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                        class="feather feather-menu">
                        <line x1="3" y1="12" x2="21" y2="12"></line>
                        <line x1="3" y1="6" x2="21" y2="6"></line>
                        <line x1="3" y1="18" x2="21" y2="18"></line>
                    </svg>
                </a>
                <div class="d-flex breadcrumb-content">
                    <div class="page-header">

                        <div class="page-title">
                        </div>

                        <nav class="breadcrumb-style-one" aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item active "> Admins </li>
                            </ol>
                        </nav>

                    </div>
                </div>
            </header>
        </div>
    </div>
    <br>
    <!--  END BREADCRUMBS  -->


    <!-- Content -->
    <div class="col-12" style="margin:2% 2% auto;">
        <div class="user-profile ">
            <div class="widget-content widget-content-area">

                <div class="" style="padding: 2%;">
                    <div class="container">
                        <div class="table-responsive" id="t1">
                            <a class="btn btn-primary mb-4 mt-4 me-4" href="{{route('admin_panel.property_owner.create')}}"> Add
                            Property Owner </a>

                            <table id="myTable1" class="table table-striped table-bordered table-sm">
                                <thead>
                                    <tr>
                                        <th class="text-center" scope="col"></th>
                                        <th scope="col"> Name</th>
                                        <th scope="col">Email</th>
                                        <th scope="col"> password</th>


                                        <th class="text-center" scope="col">Action</th>
                                    </tr>
                                </thead>
                                <tbody>


                                    <?php $counter=1;?>
                                    @foreach($item as $item)

                                    <tr>

                                        <td>
                                            <p class="text-center">{{$counter}}</p>
                                            <span class="text-success"></span>
                                            <?php $counter++;?>
                                        </td>

                                        <td>
                                            <p class="mb-0">{{$item->name}}</p>
                                            <span class="text-success"></span>
                                        </td>
                                        <td>
                                            <p class="mb-0">{{$item->email}}</p>
                                            <span class="text-success"></span>
                                        </td>

                                        <td>

                                            <p class="mb-0">{{ \Illuminate\Support\Str::limit($item->password, 20) }}
                                            </p>
                                            <span class="text-success"></span>
                                        </td>

                                        


                                        <td class="text-center">
                                            <div class="action-btns">
                                                <a href="{{route('admin_panel.property_owner.show',$item->id)}}"
                                                    class="action-btn btn-view bs-tooltip me-2" data-toggle="tooltip"
                                                    data-placement="top" title="show">
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                                        viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                                        stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                                                        class="feather feather-eye">
                                                        <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path>
                                                        <circle cx="12" cy="12" r="3"></circle>
                                                    </svg>
                                                </a>
                                                <a href="{{route('admin_panel.property_owner.edit',$item->id)}}"
                                                    class="action-btn btn-edit bs-tooltip me-2" data-toggle="tooltip"
                                                    data-placement="top" title="edit">
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                                        viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                                        stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                                                        class="feather feather-edit-2">
                                                        <path
                                                            d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z">
                                                        </path>
                                                    </svg>
                                                </a>


                                                <a href="/admin_panel/del_owner/{{$item->id}}"
                                                    class="action-btn btn-delete bs-tooltip" data-toggle="tooltip"
                                                    data-placement="top" title="delete">
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                                        viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                                        stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                                                        class="feather feather-trash-2">
                                                        <polyline points="3 6 5 6 21 6"></polyline>
                                                        <path
                                                            d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2">
                                                        </path>
                                                        <line x1="10" y1="11" x2="10" y2="17"></line>
                                                        <line x1="14" y1="11" x2="14" y2="17"></line>
                                                    </svg>
                                                </a>
                                                <a href="/admin_panel/changePass/{{$item->id}}"
                                                    class="action-btn btn-edit bs-tooltip me-2" data-toggle="tooltip"
                                                    data-placement="top" title="edit password">
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                                        viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                                        stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                                                        class="feather feather-lock">
                                                        <rect x="3" y="11" width="18" height="11" rx="2" ry="2"></rect>
                                                        <path d="M7 11V7a5 5 0 0 1 10 0v4"></path>
                                                    </svg> </a>
                                            </div>
                                        </td>
                                    </tr>

                                    @endforeach

                                </tbody>

                            </table>



                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--  BEGIN FOOTER  -->
    @include('admin.layouts.footer')
    <!--  END FOOTER  -->

    @endsection

resources/views/admin/property_owner/show.blade.php
@extends('admin.dashboard')

@section('content')

    <div id="content" class="main-content">
        <!--  BEGIN BREADCRUMBS  -->
        <div class="secondary-nav">
            <div class="breadcrumbs-container" data-page-heading="Analytics">
                <header class="header navbar navbar-expand-sm">
                    <a href="javascript:void(0);" class="btn-toggle sidebarCollapse" data-placement="bottom">
                        <svg xmlns="http://www.w3.org/2000/.svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-menu"><line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="18" x2="21" y2="18"></line></svg>
                    </a>
                    <div class="d-flex breadcrumb-content">
                        <div class="page-header">

                            <div class="page-title">
                            </div>

                            <nav class="breadcrumb-style-one" aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"> Property Owner </li>
                                    <li class="breadcrumb-item active">View Property Owner information</li>
                                </ol>
                            </nav>

                        </div>
                    </div>
                </header>
            </div>
        </div>
        <br>
        <!--  END BREADCRUMBS  -->

        <div class="row layout-spacing " >

            <!-- Content -->
            <div class="col-12" style="margin:2% 2% auto;">
                <div class="user-profile ">
                    <div class="widget-content widget-content-area">
                        <div class=" " style="padding:2% 2% 0px; " >
                            <h3 class=""> Property Owner information </h3>
                          </div>
                        <div class="" style="padding: 2%; font-weight: bold;">
                            <div class="container">

                                <div class="col-md-6">
                                    <label  >  Name  : </label>
                                    <span>{{$item->name}}</span>
                                </div>
                                <div class="col-md-6">
                                    <label  >    Email : </label>
                                    <span>{{$item->email}}</span>
                                </div>
                            </div>

                        </div>

                        </div>
                    </div>
                </div>
            </div>


        <!--  BEGIN FOOTER  -->
    @include('admin.layouts.footer')
    <!--  END FOOTER  -->
    </div>



@endsection