routes/web.php
<?php

use App\Http\Controllers\admin\AdminController;
use App\Http\Controllers\admin\ChaletsController;
use App\Http\Controllers\admin\PropertyOwnerController;
use App\Http\Controllers\admin\TestimoniosController;
use App\Http\Controllers\auth\LoginController;
use App\Http\Controllers\auth\RegisterController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\admin\AboutController;

use App\Http\Controllers\admin\ContactController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\SliderController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/login_view', [LoginController::class, 'showAdminLoginForm'])->name('admin_login');


Route::post('/login', [LoginController::class, 'login']);

Route::group(['prefix' => 'admin_panel','as' => 'admin_panel.'], function () {

    Route::group(['middleware' => 'auth:admin'], function () {

        Route::resource('about', AboutController::class);

        Route::resource('testimonials', TestimoniosController::class);
        Route::get('/del_testimonials/{id}', [TestimoniosController::class, 'destroy']);


        Route::resource('admin', AdminController::class);
        Route::get('/del_admin/{id}', [AdminController::class, 'destroy']);
        Route::get('/changePass/{id}', [AdminController::class, 'changePass']);
        Route::post('changePass/updatepass/{id}', [AdminController::class, 'updatepass']);

        
        Route::resource('property_owner', PropertyOwnerController::class);
        Route::get('/del_owner/{id}', [PropertyOwnerController::class, 'destroy']);
        Route::get('/changePass/{id}', [PropertyOwnerController::class, 'changePass']);
        Route::post('changePass/updatepass/{id}', [PropertyOwnerController::class, 'updatepass']);

       
        
     


        Route::resource('Chalets', ChaletsController::class);
        Route::get('/del_Chalets/{id}', [ChaletsController::class, 'destroy']);

        Route::resource('contact', ContactController::class);
        Route::get('/delContact/{id}', [ContactController::class, 'destroy']);

        Route::get('/logout', [LoginController::class, 'logout']);

    });
});




Route::get('/', [HomeController::class, 'index']);
Route::get('/view_chalet/{id}', [HomeController::class, 'view_chalet'])->name('views');
Route::get('/view_about', [HomeController::class, 'view_about']);

Route::get('/view_contact', [HomeController::class, 'view_contact']);

Route::post('/contact', [ContactController::class, 'store']);

Route::get('/privacy', function () {
    return view('privacy');
});
 //Clear route cache
 Route::get('/route-cache', function() {
     \Artisan::call('route:cache');
     return 'Routes cache cleared';
 });

 //Clear config cache
 Route::get('/config-cache', function() {
     \Artisan::call('config:cache');
     return 'Config cache cleared';
 }); 

 // Clear application cache
 Route::get('/clear-cache', function() {
     \Artisan::call('cache:clear');
     return 'Application cache cleared';
 });

 // Clear view cache
 Route::get('/view-clear', function() {
     \Artisan::call('view:clear');
     return 'View cache cleared';
 });

 // Clear cache using reoptimized class
 Route::get('/optimize-clear', function() {
     \Artisan::call('optimize:clear');
     return 'View cache cleared';
 });




     

   

      

app/Models/Contact.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    use HasFactory;
    protected $fillable = ['name','email','subject','message'];
}

app/Http/Controllers/admin/ContactController.php
<?php


namespace App\Http\Controllers\admin;

use App\Models\Contact;
use Illuminate\Http\Request;
use App\Mail\ContactMail;
use App\Http\Controllers\Controller;
use Validator;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Session;

class ContactController extends Controller
{

    public function index()
    {
        $contact = Contact::orderBy('created_at', 'desc')->get();
        return view('admin.contact.index', ['contact' => $contact]);
    }

    public function show($id)
    {
        $contact = Contact::find($id);
        return view('admin.contact.show', ['contact' => $contact]);
    }

   
        public function store(Request $request)
        {
          
            $validator = Validator::make($request->all(), [
                'name' => 'required',
                'email' => 'required|email',
                'subject' => 'required',
                'message' => 'required',
                
            ]);
    


            if ($validator->passes()) {

          

                $details = [
                    'name' => $request->name,
                    'email' => $request->email,
                    'subject' => $request->subject,
                    'message' => $request->message,
                ];
        
                Mail::to('maiahmad0993@gmail.com')->send(new ContactMail($details));
        
                $contact = new Contact();
                $contact->name = $request->name;
                $contact->email = $request->email;
                $contact->subject = $request->subject;
                $contact->message = $request->message;
                $contact->save();
    
               
                
            }
            else{
    
            return response()->json(['error'=>$validator->errors()]);
            }
        


      
        }


    


    public function destroy($id)
    {
        $contact = Contact::find($id);
        $contact->delete();
        return redirect()->back()->with(['message' => 'Deleted successfully  ']);
    }
}

resources/views/admin/contact/index.blade.php
@extends('admin.dashboard')

@section('content')
    <div id="content" class="main-content">
        <!--  BEGIN BREADCRUMBS  -->
        <div class="secondary-nav">
            <div class="breadcrumbs-container" data-page-heading="Analytics">
                <header class="header navbar navbar-expand-sm">
                    <a href="javascript:void(0);" class="btn-toggle sidebarCollapse" data-placement="bottom">
                        <svg xmlns="http://www.w3.org/2000/.svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-menu"><line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="18" x2="21" y2="18"></line></svg>
                    </a>
                    <div class="d-flex breadcrumb-content">
                        <div class="page-header">

                            <div class="page-title">
                            </div>

                            <nav class="breadcrumb-style-one" aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item active "> Contact Us </li>
                                </ol>
                            </nav>

                        </div>
                    </div>
                </header>
            </div>
        </div>
        <br>
        <!--  END BREADCRUMBS  -->


            <!-- Content -->
            <div class="col-12" style="margin:2% 2% auto;">
                <div class="user-profile ">
                    <div class="widget-content widget-content-area">

                        <div class="" style="padding: 2%;">
                            <div class="container">
                                  <div class="table-responsive" id="t1">
                                    <table id="myTable1" class="table table-striped table-bordered table-sm">
                                        <thead>
                                        <tr>
                                            <th class="text-center" scope="col"></th>
                                            <th scope="col"> Name</th>
                                            <th scope="col">Email</th>
                                            <th scope="col"> Subject</th>
                                            <th scope="col">Message</th>
                                            
                                            
                                            <th class="text-center" scope="col">Action</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                            

                                        <?php $counter=1;?>
                                        @foreach($contact as $contact)

                                            <tr>

                                                <td>
                                                    <p class="text-center">{{$counter}}</p>
                                                    <span class="text-success"></span>
                                                    <?php $counter++;?>
                                                </td>
                                             
                                                <td>
                                                    <p class="mb-0">{{$contact->name}}</p>
                                                    <span class="text-success"></span>
                                                </td>
                                                <td>
                                                    <p class="mb-0">{{$contact->email}}</p>
                                                    <span class="text-success"></span>
                                                </td>
                                          
                                                <td>
                                                    <p class="mb-0">{{ \Illuminate\Support\Str::limit($contact->subject, 20) }}</p>
                                                    <span class="text-success"></span>
                                                </td>
                                          
                                                <td>
                                                    <p class="mb-0">{{ \Illuminate\Support\Str::limit($contact->message, 20) }}</p>
                                                    <span class="text-success"></span>
                                                </td>
                                          
                                          


                                                <td class="text-center">
                                                    <div class="action-btns">
                                                    <a href="{{route('admin_panel.contact.show',$contact->id)}}" class="action-btn btn-view bs-tooltip me-2" data-toggle="tooltip" data-placement="top" title="show">
                                                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-eye"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg>
                                                        </a>
                                                        <a href="/admin_panel/delContact/{{$contact->id}}" class="action-btn btn-delete bs-tooltip" data-toggle="tooltip" data-placement="top" title="delete">
                                                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash-2"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path><line x1="10" y1="11" x2="10" y2="17"></line><line x1="14" y1="11" x2="14" y2="17"></line></svg>
                                                        </a>

                                                    </div>
                                                </td>
                                            </tr>

                                        @endforeach

                                        </tbody>

                                    </table>



                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        </div>

        <!--  BEGIN FOOTER  -->
    @include('admin.layouts.footer')
    <!--  END FOOTER  -->

@endsection

resources/views/admin/contact/show.blade.php
@extends('admin.dashboard')

@section('content')

    <div id="content" class="main-content">
        <!--  BEGIN BREADCRUMBS  -->
        <div class="secondary-nav">
            <div class="breadcrumbs-container" data-page-heading="Analytics">
                <header class="header navbar navbar-expand-sm">
                    <a href="javascript:void(0);" class="btn-toggle sidebarCollapse" data-placement="bottom">
                        <svg xmlns="http://www.w3.org/2000/.svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-menu"><line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="18" x2="21" y2="18"></line></svg>
                    </a>
                    <div class="d-flex breadcrumb-content">
                        <div class="page-header">

                            <div class="page-title">
                            </div>

                            <nav class="breadcrumb-style-one" aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"> Contact Us </li>
                                    <li class="breadcrumb-item active">View communication request</li>
                                </ol>
                            </nav>

                        </div>
                    </div>
                </header>
            </div>
        </div>
        <br>
        <!--  END BREADCRUMBS  -->

        <div class="row layout-spacing " >

            <!-- Content -->
            <div class="col-12" style="margin:2% 2% auto;">
                <div class="user-profile ">
                    <div class="widget-content widget-content-area">
                        <div class=" " style="padding:2% 2% 0px; " >
                            <h3 class=""> Contact request information </h3>
                          </div>
                        <div class="" style="padding: 2%; font-weight: bold;">
                            <div class="container">

                                <div class="col-md-6">
                                    <label  >  Name  : </label>
                                    <span>{{$contact->name}}</span>
                                </div>
                                <div class="col-md-6">
                                    <label  >    Email : </label>
                                    <span>{{$contact->email}}</span>
                                </div>
                                <div class="col-md-6">
                                    <label  >    Subject: </label>
                                    <span>{{$contact->subject}}</span>
                                </div>
                                <div class="col-md-6">
                                    <label  > Message    : </label>
                                    <span>{{$contact->message}}</span>
                                </div>
                            </div>

                        </div>

                        </div>
                    </div>
                </div>
            </div>


        <!--  BEGIN FOOTER  -->
    @include('admin.layouts.footer')
    <!--  END FOOTER  -->
    </div>



@endsection