routes/web.php
<?php

use App\Http\Controllers\admin\AdminController;
use App\Http\Controllers\admin\ChaletsController;
use App\Http\Controllers\admin\PropertyOwnerController;
use App\Http\Controllers\admin\TestimoniosController;
use App\Http\Controllers\auth\LoginController;
use App\Http\Controllers\auth\RegisterController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\admin\AboutController;

use App\Http\Controllers\admin\ContactController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\SliderController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/login_view', [LoginController::class, 'showAdminLoginForm'])->name('admin_login');


Route::post('/login', [LoginController::class, 'login']);

Route::group(['prefix' => 'admin_panel','as' => 'admin_panel.'], function () {

    Route::group(['middleware' => 'auth:admin'], function () {

        Route::resource('about', AboutController::class);

        Route::resource('testimonials', TestimoniosController::class);
        Route::get('/del_testimonials/{id}', [TestimoniosController::class, 'destroy']);


        Route::resource('admin', AdminController::class);
        Route::get('/del_admin/{id}', [AdminController::class, 'destroy']);
        Route::get('/changePass/{id}', [AdminController::class, 'changePass']);
        Route::post('changePass/updatepass/{id}', [AdminController::class, 'updatepass']);

        
        Route::resource('property_owner', PropertyOwnerController::class);
        Route::get('/del_owner/{id}', [PropertyOwnerController::class, 'destroy']);
        Route::get('/changePass/{id}', [PropertyOwnerController::class, 'changePass']);
        Route::post('changePass/updatepass/{id}', [PropertyOwnerController::class, 'updatepass']);

       
        
     


        Route::resource('Chalets', ChaletsController::class);
        Route::get('/del_Chalets/{id}', [ChaletsController::class, 'destroy']);

        Route::resource('contact', ContactController::class);
        Route::get('/delContact/{id}', [ContactController::class, 'destroy']);

        Route::get('/logout', [LoginController::class, 'logout']);

    });
});




Route::get('/', [HomeController::class, 'index']);
Route::get('/view_chalet/{id}', [HomeController::class, 'view_chalet'])->name('views');
Route::get('/view_about', [HomeController::class, 'view_about']);

Route::get('/view_contact', [HomeController::class, 'view_contact']);

Route::post('/contact', [ContactController::class, 'store']);

Route::get('/privacy', function () {
    return view('privacy');
});
 //Clear route cache
 Route::get('/route-cache', function() {
     \Artisan::call('route:cache');
     return 'Routes cache cleared';
 });

 //Clear config cache
 Route::get('/config-cache', function() {
     \Artisan::call('config:cache');
     return 'Config cache cleared';
 }); 

 // Clear application cache
 Route::get('/clear-cache', function() {
     \Artisan::call('cache:clear');
     return 'Application cache cleared';
 });

 // Clear view cache
 Route::get('/view-clear', function() {
     \Artisan::call('view:clear');
     return 'View cache cleared';
 });

 // Clear cache using reoptimized class
 Route::get('/optimize-clear', function() {
     \Artisan::call('optimize:clear');
     return 'View cache cleared';
 });




     

   

      

app/Models/Chalets.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasMany;

use Illuminate\Database\Eloquent\Model;
use App\Models\Chalets_image;



class Chalets extends Model
{
    use HasFactory;
    protected $fillable = [
        'title',
        'image',
    ];


    public function  ChaletImage()
    {
        return $this->hasMany(Chalets_image::class);
    }
 
}

app/Http/Controllers/admin/ChaletsController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use App\Models\Chalets;
use App\Models\Chalets_image;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;

class ChaletsController extends Controller
{


    public function index()
    {
        $item = Chalets::orderBy('created_at', 'desc')->get();
        return view('admin.chalets.index', compact('item'));
    }



    public function create()
    {
        return view('admin.chalets.create');
    }



    public function store(Request $request)
    {
        // 
        $item = Chalets::create([
            'title' => $request->title,

        ]);

        if ($request->image != '') {
            $path = 'images/Chalets/';
            $file = $request->image;
            $filename = $file->getClientOriginalName();
            $filename =  $path . time() . $filename;
            $file->move($path, $filename);

            $item->update([
                'image' => $filename
            ]);
        }



        $images = [];
        if ($request->chalet_image != '') {
            $path = 'images/Chalets/';
            foreach ($request->chalet_image as $key => $image) {
                $imageName = $image->getClientOriginalName();
                $imageName = $path .time(). $imageName;
                $image->move(public_path('images/Chalets/'), $imageName);
                $images[] = $imageName;
            }


            foreach ($images as $key => $image) {

                Chalets_image::create([
                    'chalets_id' => $item->id,
                    'image_chalet' => $image
                ]);
            }
        }

        return redirect(route('admin_panel.Chalets.index'));
    }

    public function show($id)
    {
        $item = Chalets::find($id);
        $item_image = Chalets_image::where('chalets_id', $id)->get();
        return view('admin.chalets.item', compact('item', 'item_image'));
    }


    public function edit(Request $request, $id )
    {
        $item = Chalets::find($id);
        $item_image = Chalets_image::where('chalets_id', $id)->get();
        return view('admin.chalets.edit', compact('item', 'item_image'));
    }



    public function update(Request $request, $id)
    {
        // 

        $item = Chalets::find($id);

        if ($request->image != '') {
            (File::exists($item->image)) ? File::delete($item->image) : Null;
            $path = 'images/Chalets/';
            $file = $request->image;
            $filename = $file->getClientOriginalName();
            $filename = $path . time() . $filename;
            $file->move($path, $filename);

            $item->update([
                'image' => $filename
            ]);
        }

        $item->update([
            'title' => $request->title,
        ]);
     
           


        $images = [];
        if ($request->chalet_image != '') {

         

            $item_chalets= Chalets_image::where('chalets_id', $id)->with('category')->get();

            foreach($item_chalets as $item_chalets){
                if($item_chalets->image_chalet!='1'){
                    $item_chalets->delete();
               (File::exists($item_chalets->image_chalet)) ? File::delete($item_chalets->image_chalet): Null;

            }

        }
            $path = 'images/Chalets/';

            foreach ($request->chalet_image as $key => $image) {
                $imageName = $image->getClientOriginalName();
                $imageName = $path .time(). $imageName;
                $image->move(public_path('images/Chalets/'), $imageName);
                $images[] = $imageName;
            }
            foreach ($images as $key => $image) {

                Chalets_image::create([
                    'chalets_id' => $item->id,
                    'image_chalet' => $image
                ]);
            }
        }

        return redirect(route('admin_panel.Chalets.index'));

    }

    public function destroy($id)
    {

        $item = Chalets::find($id);
        $item_chalets= Chalets_image::where('chalets_id', $id)->with('category')->get();
        $item->delete();
      

        if($item->image!='images/avatar.png'){
            (File::exists($item->image)) ? File::delete($item->image) : Null;
        }

        foreach($item_chalets as $item_chalets){
            if($item_chalets->image_chalet!='1'){
                $item_chalets->delete();
           (File::exists($item_chalets->image_chalet)) ? File::delete($item_chalets->image_chalet): Null;

        }
    }
    return redirect(route('admin_panel.Chalets.index'));


    }
}

resources/views/admin/chalets/create.blade.php
@extends('admin.dashboard')

@section('content')

    <div id="content" class="main-content">
        <!--  BEGIN BREADCRUMBS  -->
        <div class="secondary-nav">
            <div class="breadcrumbs-container" data-page-heading="Analytics">
                <header class="header navbar navbar-expand-sm">
                    <a href="javascript:void(0);" class="btn-toggle sidebarCollapse" data-placement="bottom">
                        <svg xmlns="http://www.w3.org/2000/.svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-menu"><line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="18" x2="21" y2="18"></line></svg>
                    </a>
                    <div class="d-flex breadcrumb-content">
                        <div class="page-header">

                            <div class="page-title">
                            </div>

                            <nav class="breadcrumb-style-one" aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item ">  Chalets </li>
                                    <li class="breadcrumb-item active"> Chalet </li>
                                </ol>
                            </nav>

                        </div>
                    </div>
                </header>
            </div>
        </div>
        <br>
        <!--  END BREADCRUMBS  -->
        <div class="row layout-spacing " >

            <!-- Content -->
            <div class="col-12" style="margin:2% 2% auto;">
                <div class="user-profile ">
                    <div class="widget-content widget-content-area">
                        <div class=" " style="padding:2% 2% 0px; " >
                            <h3 class="">Add Chalets</h3>
                        </div>

                        <div class="" style="padding: 2%;">
                            <div class="container">
                                <form class=" g-3" method="post" action="{{route('admin_panel.Chalets.store')}}" enctype="multipart/form-data" >
                                    @method('POST')
                                    @csrf
                                    @if ($errors->any())

                                        <div class="alert alert-danger">

                                            <ul style="list-style: none;margin:0">

                                                @foreach ($errors->all() as $error)

                                                    <li>{{ $error }}</li>

                                                @endforeach

                                            </ul>

                                        </div>

                                    @endif
                                    <div class="row">

                                    <div class="col-md-12">
                                            <h5>  Title </h5>
                                            <input type="text" class="form-control"  name="title" required>
                                        </div>

                                        <div class="col-md-12">
                                            <h5>  Main Image </h5>
                                            <input type="file" class="form-control" name="image" >
                                        </div>

                                       
                                        <div class="col-12">
                                            <h5>  Chalets Images </h5>
                                            <input type="file" class="form-control" name="chalet_image[]" multiple >
                                        </div>

                                        <div class="col-12">
                                            <div class="text-center">
                                                <button type="submit" class="btn btn-primary">Add </button>
                                            </div>
                                        </div>

                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>



        <!--  BEGIN FOOTER  -->
    @include('admin.layouts.footer')
    <!--  END FOOTER  -->

    </div>



@endsection

resources/views/admin/chalets/edit.blade.php
@extends('admin.dashboard')

@section('content')

    <div id="content" class="main-content">
        <!--  BEGIN BREADCRUMBS  -->
        <div class="secondary-nav">
            <div class="breadcrumbs-container" data-page-heading="Analytics">
                <header class="header navbar navbar-expand-sm">
                    <a href="javascript:void(0);" class="btn-toggle sidebarCollapse" data-placement="bottom">
                        <svg xmlns="http://www.w3.org/2000/.svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-menu"><line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="18" x2="21" y2="18"></line></svg>
                    </a>
                    <div class="d-flex breadcrumb-content">
                        <div class="page-header">

                            <div class="page-title">
                            </div>

                            <nav class="breadcrumb-style-one" aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                <li class="breadcrumb-item ">  Testimonials </li>
                                    <li class="breadcrumb-item active"> Testimonial </li>
                                </ol>
                            </nav>

                        </div>
                    </div>
                </header>
            </div>
        </div>
        <br>
        <!--  END BREADCRUMBS  -->
        <div class="row layout-spacing " >

            <!-- Content -->
            <div class="col-12" style="margin:2% 2% auto;">
                <div class="user-profile ">
                    <div class="widget-content widget-content-area">
                        <div class=" " style="padding:2% 2% 0px; " >
                            <h3 class="">Edit Testimonial  </h3>
                        </div>

                        <div class="" style="padding: 2%;">
                            <div class="container">
                                <form class=" g-3" method="post" action="{{route('admin_panel.Chalets.update',$item->id)}}" enctype="multipart/form-data" >
                                @method('PATCH')
                                    @csrf
                                    @if ($errors->any())

                                        <div class="alert alert-danger">

                                            <ul style="list-style: none;margin:0">

                                                @foreach ($errors->all() as $error)

                                                    <li>{{ $error }}</li>

                                                @endforeach

                                            </ul>

                                        </div>

                                    @endif
                                    <div class="col-md-12">
                                        <img alt="avatar" src="{{asset($item->image)}}"  width="200" height="200"/>
                                        <br><br>
                                        <input type="file" class="form-control"  name="image" >
                                    </div>

                                    <div class="col-md-12">
                                        <label for="inputEmail4" class="form-label">  Title </label>
                                        <input type="text" class="form-control"  name="title"  value="{{$item->title}}">
                                    </div>




                                    <div class="col-12">
                                            <label for="inputAddress" class="form-label"> Chalet image </label>
                                            <input type="file" class="form-control" name="chalet_image[]" multiple >
                                        </div>
                                




                                    <div class="col-12">
                                        <div class="text-center">
                                        <button type="submit" class="btn btn-primary">Update</button>
                                        </div>
                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        @section('script-editor')
    <script>
          $('#summernote').summernote({

      });
    </script>
    @endsection

        <!--  BEGIN FOOTER  -->
    @include('admin.layouts.footer')
    <!--  END FOOTER  -->

    </div>



@endsection

resources/views/admin/chalets/index.blade.php
@extends('admin.dashboard')

@section('content')
    <div id="content" class="main-content">
        <!--  BEGIN BREADCRUMBS  -->
        <div class="secondary-nav">
            <div class="breadcrumbs-container" data-page-heading="Analytics">
                <header class="header navbar navbar-expand-sm">
                    <a href="javascript:void(0);" class="btn-toggle sidebarCollapse" data-placement="bottom">
                        <svg xmlns="http://www.w3.org/2000/.svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-menu"><line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="18" x2="21" y2="18"></line></svg>
                    </a>
                    <div class="d-flex breadcrumb-content">
                        <div class="page-header">

                            <div class="page-title">
                            </div>

                            <nav class="breadcrumb-style-one" aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item active "> Chalets </li>
                                </ol>
                            </nav>

                        </div>
                    </div>
                </header>
            </div>
        </div>
        <br>
        <!--  END BREADCRUMBS  -->


            <!-- Content -->
            <div class="col-12" style="margin:2% 2% auto;">
                <div class="user-profile ">
                    <div class="widget-content widget-content-area">

                        <div class="" style="padding: 2%;">
                            <div class="container">
                                  <div class="table-responsive" id="t1">
                                    <a class="btn btn-primary mb-4 mt-4 me-4" href="{{route('admin_panel.Chalets.create')}}"> Add Chalets  </a>
                                    <table id="myTable1" class="table table-striped table-bordered table-sm">
                                        <thead>
                                        <tr>
                                            <th class="text-center" scope="col"></th>
                                            <th scope="col"> Image</th>
                                            <th scope="col">Title</th>
                                            
                                            
                                            <th class="text-center" scope="col">Action</th>
                                        </tr>
                                        </thead>
                                        <tbody>

                                        <?php $counter=1;?>
                                        @foreach($item as $item)

                                            <tr>

                                                <td>
                                                    <p class="text-center">{{$counter}}</p>
                                                    <span class="text-success"></span>
                                                    <?php $counter++;?>
                                                </td>
                                                <td>
                                                    <div class="media">
                                                        <div class="avatar me-2">
                                                            <img alt="avatar" src="{{asset($item->image)}}" class="rounded-circle" />
                                                        </div>

                                                    </div>
                                                </td>
                                                <td>
                                                    <p class="mb-0">{{$item->title}}</p>
                                                    <span class="text-success"></span>
                                                </td>
                                          


                                                <td class="text-center">
                                                    <div class="action-btns">
                                                        <a href="{{route('admin_panel.Chalets.show',$item->id)}}" class="action-btn btn-view bs-tooltip me-2" data-toggle="tooltip" data-placement="top" title="show">
                                                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-eye"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg>
                                                        </a>
                                                        <a href="{{route('admin_panel.Chalets.edit',$item->id)}}" class="action-btn btn-edit bs-tooltip me-2" data-toggle="tooltip" data-placement="top" title="edit">
                                                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit-2"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path></svg>
                                                        </a>
                                                        <a href="/admin_panel/del_Chalets/{{$item->id}}" class="action-btn btn-delete bs-tooltip" data-toggle="tooltip" data-placement="top" title="delete">
                                                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash-2"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path><line x1="10" y1="11" x2="10" y2="17"></line><line x1="14" y1="11" x2="14" y2="17"></line></svg>
                                                        </a>

                                                    </div>
                                                </td>
                                            </tr>

                                        @endforeach

                                        </tbody>

                                    </table>



                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        </div>

        <!--  BEGIN FOOTER  -->
    @include('admin.layouts.footer')
    <!--  END FOOTER  -->

@endsection

resources/views/admin/chalets/item.blade.php
@extends('admin.dashboard')

@section('content')

<div id="content" class="main-content">
    <!--  BEGIN BREADCRUMBS  -->
    <div class="secondary-nav">
        <div class="breadcrumbs-container" data-page-heading="Analytics">
            <header class="header navbar navbar-expand-sm">
                <a href="javascript:void(0);" class="btn-toggle sidebarCollapse" data-placement="bottom">
                    <svg xmlns="http://www.w3.org/2000/.svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                        class="feather feather-menu">
                        <line x1="3" y1="12" x2="21" y2="12"></line>
                        <line x1="3" y1="6" x2="21" y2="6"></line>
                        <line x1="3" y1="18" x2="21" y2="18"></line>
                    </svg>
                </a>
                <div class="d-flex breadcrumb-content">
                    <div class="page-header">

                        <div class="page-title">
                        </div>

                        <nav class="breadcrumb-style-one" aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"> Testimonials </li>
                                <li class="breadcrumb-item active"> Testimonial </li>
                            </ol>
                        </nav>

                    </div>
                </div>
            </header>
        </div>
    </div>
    <br>
    <!--  END BREADCRUMBS  -->

    <div class="row layout-spacing ">

        <!-- Content -->
        <div class="col-12" style="margin:2% 2% auto;">
            <div class="user-profile ">
                <div class="widget-content widget-content-area">
                    <div class=" " style="padding:2% 2% 0px; ">
                        <h3 class="">Show Shalets</h3>
                    </div>
                    <div class="" style="padding: 2%; font-weight: bold;">
                        <div class="container">
                            <div class="row mb-4">
                                <div class="col-md-12 mb-4">
                                    <h5 style="display:inline"> Title : </h5>
                                    <span >{{$item->title}}</span>
                                </div>
                                <div class="col-md-12 mb-4">
                                    <h5> Main Image </h5>
                                    <img alt="avatar" src="{{asset($item->image)}}" width="200" height="200" />
                                    <br><br>
                                </div>
                            </div>
                            <div class="row ">
                                <h5>
                                    Chalet Images
                                </h5>
                                @foreach($item_image as $item)
                                <div class="col-md-3">
                                    <img alt="avatar" src="{{asset($item->image_chalet)}}" width="200" height="200" />
                                    <br><br>
                                </div>
                                @endforeach
                            </div>

                        </div>

                    </div>

                </div>
            </div>
        </div>
    </div>


    <!--  BEGIN FOOTER  -->
    @include('admin.layouts.footer')
    <!--  END FOOTER  -->
</div>



@endsection